#!/data/data/com.termux/files/usr/bin/bash -e

function unsupported_arch() {
    print_prefix_banner
    printf "${red}[*] Unsupported Architecture${reset}\n"
    echo "You have successfully logged out."
    exit
}

function ask() {
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi
        printf "${light_cyan}\n[?] "
        read -p "$1 [$prompt] " REPLY
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi
        printf "${reset}"
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) prefix || :
                   return 1 ;;
        esac
    done
}

function ask_switch_32() {
    while true; do
        printf "${light_cyan}\n[?] ";read -p "$1 [y/N] " REPLY;printf "${reset}"
        if [ -z "$REPLY" ]; then
            REPLY=N
        fi
        case "$REPLY" in
            Y*|y*) warning_msg;revert32;exit;;
            N*|n*) revert32;exit;;
        esac
    done
}

function get_version() {
    printf "${blue}[*] Checking device android version...${reset}\n\n"
    case "$(getprop ro.build.version.release)" in
        4*|5*|6*)
            printf "${yellow}Android 4/5/6 isn't supported${reset}\n\n"
            exit
            ;;
        *)
            printf "${yellow}Your device's Android version is $(getprop ro.build.version.release)${reset}\n\n"
            ;;
    esac
}

function check_dependencies() {
    printf "${blue}\n[*] Checking package dependencies...${reset}\n"
    ## Workaround for termux-app issue #1283 (https://github.com/termux/termux-app/issues/1283)
    ##apt update -y &> /dev/null
    apt-get update -y &> /dev/null || apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade -y &> /dev/null
    for i in unzip axel play-audio; do
        if [ -e $PREFIX/bin/$i ]; then
            echo "  $i is OK"
        else
            printf "Installing ${i}...\n"
            apt install -y $i || {
                printf "${red}ERROR: Failed to install packages.\n Exiting.\n${reset}"
	        exit
            }
        fi
    done
    printf "\033[1;35mapt upgrade starting...${reset}\n"
    apt upgrade -y || {
        printf "\n${red}ERROR: Failed to upgrade packages.\n_______Please check the internet connection.\n\n"
        read -p "$1[?] Do you want continue any way ??? [y/N] " ANS;printf "\n${reset}"
        case "$ANS" in
            *y*|*Y*) echo "Continuing any way.";return 0;;
            *) echo "You have successfully logged out.";exit;;
        esac
    }
}

function welcome_voice() {
  if ask "Do you want continue with welcome voice" "Y"; then
     printf "${yellow}Continuing Anyway${reset}\n\n"
     bootstrap_dir
  fi
}
function bootstrap_dir() {
     check_Bootstrap_directory
     check_dependencies
    if [ -f /sdcard/Termux-Bootstrap/welcome.mp3 ];then
        printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
        play-audio /sdcard/Termux-Bootstrap/welcome.mp3
    else
        axel --output=/sdcard/Termux-Bootstrap/welcome.mp3 https://github.com/shahinuralamin/Technical_Shahinur_Al-Amin/releases/download/termux-prefix-switcher/welcome.mp3 &> /dev/null || {
             printf "${red}E: Internet connection error ${reset}\n"
             return 0
        }
        printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
        play-audio /sdcard/Termux-Bootstrap/welcome.mp3
    fi
}


function print-help() {
    HEIGHT=21
    WIDTH=39
    CHOICE_HEIGHT=4
    BACKTITLE="Termux Prefix Switcher (version 1.3)"
    TITLE="Help"
    MENU="Allows to switch 32-bit termux environment on 64-bit devices Options: help - show this help switch - Switches to 32-bit Mode revert - Reverts to 64-bit Mode (This Uninstalls 32-bit prefix) NOTE: Switching to 32-bit will not install packages automatically so you have to install them again if possible."


    OPTIONS=(1 "[ Home ]"
             2 " Switch "
             3 " Revert ")

    CHOICE=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --title "$TITLE" \
                    --menu "$MENU" \
                    $HEIGHT $WIDTH $CHOICE_HEIGHT \
                    "${OPTIONS[@]}" \
                    2>&1 >/dev/tty)

    clear
    case $CHOICE in
            1)
                prefix
                ;;
            2)
                switch
                ;;
            3)
                revert
                ;;
    esac
    exit
}

function setup_storage() {
    printf "\n${green}";read -p " [#] Allow the storage permission. [Enter] ";printf "${reset}\n"
    termux-setup-storage ||:
    read -p " [#] Check the Termux storage permission. [Enter]"
    echo "check storage" >> /sdcard/.Al-Amin_Zone || {
        printf "\n\n${green} Please send 'y' command & then press 'Enter'.\n Or,${reset}"
        setup_storage
        return 0
    }
    if [ -e $HOME/storage ]; then
        echo "  Storage is OK"
        Bootstrap_directory
    else
        setup_storage
    fi
}

function Bootstrap_directory() {
    if [ ! -d /sdcard/Termux-Bootstrap ]; then
        mkdir /sdcard/Termux-Bootstrap || {
             setup_storage
             return 0
        }
        printf "${yellow} [#] Termux-Bootstrap directory created.${reset}\n\n"
    fi
}

function check_Bootstrap_directory() {
    if [ -d /sdcard/Termux-Bootstrap ]; then
        printf "${yellow}[√] Termux-Bootstrap directory found.${reset}\n"
        echo "check storage" >> /sdcard/Termux-Bootstrap/.Al-Amin_Zone || {
            setup_storage
        }
    else
        printf "${yellow}[!] Termux-Bootstrap directory not found.${reset}\n"
        Bootstrap_directory
    fi
}

function switch() {
    case "$(uname -m)" in
        armeabi|armv8l|armeabi-v7a|armv7l|i*86)
            HEIGHT=15
            WIDTH=40
            CHOICE_HEIGHT=4
            BACKTITLE="Al-Amin Zone"
            TITLE="Termux Prefix Switcher (version 1.3)"
            MENU="Cannot Switch Environment: Your device is running in 32-bit"


            OPTIONS=(1 "[ Home ]")

            CHOICE=$(dialog --clear \
                            --backtitle "$BACKTITLE" \
                            --title "$TITLE" \
                            --menu "$MENU" \
                            $HEIGHT $WIDTH $CHOICE_HEIGHT \
                            "${OPTIONS[@]}" \
                            2>&1 >/dev/tty)

            clear
            case $CHOICE in
                1)
                prefix
                ;;
            esac
            exit
            ;;
    esac
    print_banner
    check_Bootstrap_directory
    if [ -e $PREFIX/../usr32-backup ]; then
            printf "${yellow}[√] Arm 32-bit usr backup found${reset}\n\n"
            printf "${green}[★] Maybe you are already read warning message.${reset}"
            ask_switch_32 "Do you want to read again this?..."
    fi
    printf "${light_cyan}\n";read -p "[*] Some warning message view in press [Enter]";printf "${reset}";warning_msg
    if ask "Do you want to switch to 32-bit? All data in this environment will be lost" "N";then
        printf "${yellow}[!]Switching to 32-bit installation... Continuing Anyway!${reset}\n\n"
        check_dependencies
        sleep 5.5
        case "$(uname -m)" in
            aarch64|arm64-v8a|arm64-v8|arm64)
                unset KEEP_ARM
                if [ -f /sdcard/Termux-Bootstrap/bootstrap-arm.zip ]; then
                    printf "${yellow}[!] Using existing arm bootstrap archive${reset}\n"
                    KEEP_ARM=1
                fi
                if [ -z $KEEP_ARM ]; then
                    printf "${blue}[*] Downloading arm 32-bit termux bootstrap...${reset}\n"
                    axel --output=/sdcard/Termux-Bootstrap/bootstrap-arm.zip https://github.com/hop-prog/Termux-Bootstrap/raw/main/arm/bootstrap-arm.zip 2> /dev/null || {
                         printf "\n${red}[×] E: Internet Connection Error…{$reset}\n"
                    }
                fi
                if [ -f /sdcard/Termux-Bootstrap/bootstrap-arm.zip ]; then
                    # Unpack and remove existing installation
                    sleep 3
	            chmod 755 usr -R &> /dev/null ||:
	            rm -rf $PREFIX/../usr32-staging
	            printf "\n${blue}[*] Extracting arm bootstrap... ${reset}\n\n"
                    unzip -d $PREFIX/../usr32-staging /sdcard/Termux-Bootstrap/bootstrap-arm.zip &> /dev/null || {
                         echo "Bootstrap not found"
                         setup_storage
                         switch
                    }
                    printf "\n\033[1;35m[√] Extracted successfully${reset}\n"
                    scnd_stg
                fi
                ;;
            x86_64|amd64)
                unset KEEP_ARM
                if [ -f /sdcard/Termux-Bootstrap/bootstrap-i686.zip ]; then
                    printf "${yellow}[!] Using existing i686 bootstrap archive${reset}\n"
                    KEEP_ARM=1
                fi
                if [ -z $KEEP_ARM ]; then
                    printf "${blue}[*] Downloading i686 32-bit termux bootstrap...${reset}\n"
                    axel --output=/sdcard/Termux-Bootstrap/bootstrap-i686.zip https://github.com/hop-prog/Termux-Bootstrap/raw/main/arm/bootstrap-i686.zip 2> /dev/null || {
                         printf "\n${red}[×] E: Internet Connection Error…{$reset}\n"
                    }
                fi
                if [ -f /sdcard/Termux-Bootstrap/bootstrap-i686.zip ]; then
                    # Unpack and remove existing installation
                    sleep 3
                    chmod 755 usr -R &> /dev/null ||:
                    rm -rf $PREFIX/../usr32-staging
                    printf "\n${blue}[*] Extracting arm bootstrap... ${reset}\n\n"
                    unzip -d $PREFIX/../usr32-staging /sdcard/Termux-Bootstrap/bootstrap-i686.zip &> /dev/null || {
                         echo "Bootstrap not found"
                         setup_storage
                         switch
                    }
                    printf "\n\033[1;35m[√] Extracted successfully${reset}\n"
                    scnd_stg
                fi
                ;;
            *)
                unsupported_arch
                ;;
        esac
    fi
}

function warning_msg() {
    printf "\n${green}"
    echo "WARNING: You are about to enter the world of 32-bit, here's what you will expect when entering to 32-bit"
    echo "* Inconsistency will occur when running 64-bit on 32-bit environment, in some cases with the preloaded termux-exec library, you can usually unset it"
    echo "* When Running Chromium in 32-bit proot'ed linux environment, expect segmentation failures (even with --no-sandbox) option,"
    echo "* This Script will not track what packages you've installed, so you will need to reinstall them again if possible"
    echo "The Installation will begin in 5 seconds, please save all your work to avoid data loss"
    printf "${reset}"
}

function scnd_stg() {
     # Process Symlinks
     echo "[*] Processing Symlinks"
     cd $PREFIX/../usr32-staging
     while read s; do
             ln -s ${s/←/ }
     done <SYMLINKS.txt
     rm SYMLINKS.txt

     # Create Second Stage Script
     echo "[*] Doing Second Stage Setup"
     cat > $PREFIX/../secondstage-setup.sh <<- EOM
     #!/system/bin/sh
     echo "[*] Creating Backup"
     rm -rf usr64-backup
     mv usr usr64-backup
     echo "[*] Switching"
     mv usr32-staging usr
     rm secondstage-setup.sh
     echo "[✓] Done, Please Close and Reopen the app"
     sleep 2
     kill -KILL $PPID
EOM
     chmod 755 $PREFIX/../secondstage-setup.sh
     cd $PREFIX/..

     # Kill Current Process and Do Second Stage Setup
     exec /system/bin/env -i ./secondstage-setup.sh
}

function revert() {
    case "$(uname -m)" in
        arm64-v8a|arm64-v8|aarch64|arm64|x86_64|amd64)
            HEIGHT=15
            WIDTH=40
            CHOICE_HEIGHT=4
            BACKTITLE="Tecnical Shahinur_Al-Amin"
            TITLE="Termux Prefix Switcher (version 1.3)"
            MENU="This option is used to switching back to 64-bit, you're already 64-bit"


            OPTIONS=(1 "[ Home ]")

            CHOICE=$(dialog --clear \
                            --backtitle "$BACKTITLE" \
                            --title "$TITLE" \
                            --menu "$MENU" \
                            $HEIGHT $WIDTH $CHOICE_HEIGHT \
                            "${OPTIONS[@]}" \
                            2>&1 >/dev/tty)

            clear
            case $CHOICE in
                1)
                prefix
                ;;
            esac
            exit
            ;;
        armeabi|armv8l|armeabi-v7a|armv7l|i*86)
            if [ -e $PREFIX/../usr64-backup ]; then
                print_banner
                   if ask "Do you want to switch back to 64-bit? All data in this environment will be lost" "N"; then
                      printf "${yellow}[#] Switch back to 64-bit mode${reset}\n\n"
                      cd $PREFIX/..

                      # Revert Back to 64-bit
                      echo "[*] Purging 32-bit environment"
       	              cat > purge-prefix.sh <<- EOM
	              #!/system/bin/sh
                      echo "[*] Creating Backup"
                      chmod 755 usr -R &> /dev/null ||:
                      rm -rf usr32-backup
       	              mv usr usr32-backup

	              # Restore Backup directory if possible"
	              if [ -e usr64-backup ]; then
	                     echo "[*] Restoring 64-bit Prefix"
          	             mv usr64-backup usr
	              fi

	              rm -rf purge-prefix.sh

                      echo "[✓] Done, Please Close and Reopen the app"
                      sleep 2
                      kill -KILL $PPID
EOM
                      chmod 755 purge-prefix.sh

                      # Kill Current Process and Purge 32-bit prefix
                      exec /system/bin/env -i ./purge-prefix.sh
                   fi
            else
                print_banner
                printf "${blue}[*] Checking device architecture ..."
                case $(getprop ro.product.cpu.abi) in
                    arm64-v8a|arm64-v8|aarch64|arm64|x86_64|amd64)
                        printf "\n\n${green}"
                        echo "Maybe your device architecture is $(getprop ro.product.cpu.abi)[64-bit]"
                        echo "If you think you have a problem with termux prefix"
                        echo "And if your device architecture is 64-bit,"
                        echo "then you can delete termux prefix usr."
                        echo "If you delete PREFIX usr then"
                        echo "all data in this environment will be lost"
                        printf "${reset}\n"
                        if ask "Do you want delete termux prefix-usr" "N"; then
                            echo "    Deleting.....            And...."
                            printf "${yellow}[#] Switch back to 64-bit mode${reset}\n\n"
                            cd $PREFIX/..
                            echo "[*] Purging 32-bit environment"
                            cat > purge-prefix.sh <<- EOM
                            #!/system/bin/sh
                            echo "[*] Creating Backup"
                            chmod 755 usr -R &> /dev/null ||:
                            rm -rf usr32-backup
                            mv usr usr32-backup
                            rm -rf purge-prefix.sh

                            echo "[✓] Done, Please Close and Reopen the app"
                            sleep 2
                            kill -KILL $PPID
EOM
                            chmod 755 purge-prefix.sh

                            # Kill Current Process and Purge 32-bit prefix
                            exec /system/bin/env -i ./purge-prefix.sh
                        fi
                        ;;
                    armeabi|armv8l|armeabi-v7a|armv7l|i*86)
                        printf "\n\n${red}"
                        echo "Maybe your device architecture is $(getprop ro.product.cpu.abi)[32-bit]"
                        echo "[!] The Backup Directory isn't exists."
                        echo "    Or your device is unsupported maybe."
                        printf "${reset}\n\n"
                        echo "[-] Sorry... Don't switch back to 64-bit"
                        echo "[~] So sad,, Please Close and Reopen the app"
                        kill -KILL $PPID
                        exit
                        ;;
                    *)
                         unsupported_arch
                        ;;
                esac
            fi
    esac
}

function revert32() {
            # Ask for Confirmation
            if ask "Do you want to switch back to 32-bit?" "N"; then
               printf "${yellow}[#] Switch back to 32-bit mode${reset}\n\n"
               cd $PREFIX/..
               # Revert Back to 32-bit
               echo "[*] Purging 64-bit environment"
	       cat > purge-prefix32.sh <<- EOM
	       #!/system/bin/sh
	       echo "[*] Creating Backup"
               rm -rf usr64-backup
               mv usr usr64-backup
	       # Restore Backup directory if possible"
	       if [ -e usr32-backup ]; then
	              echo "[*] Restoring 32-bit Prefix"
		      mv usr32-backup usr
	       fi
	       rm -rf purge-prefix32.sh
               echo "[✓] Done, Please Close and Reopen the app"
               sleep 2
               kill -KILL $PPID
EOM
               chmod 755 purge-prefix32.sh

               # Kill Current Process and Purge 32-bit prefix
               exec /system/bin/env -i ./purge-prefix32.sh
            fi
            exit
}

function termux_arch() {
    HEIGHT=15
    WIDTH=40
    CHOICE_HEIGHT=4
    BACKTITLE="Al-Amin Zone"
    TITLE="Termux Prefix Switcher (version 1.3)"
    MENU="Your termux current architecture is $(uname -m)"
    OPTIONS=(1 "[ Home ]")
    CHOICE=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --title "$TITLE" \
                    --menu "$MENU" \
                    $HEIGHT $WIDTH $CHOICE_HEIGHT \
                    "${OPTIONS[@]}" \
                    2>&1 >/dev/tty)
    clear
    case $CHOICE in
            1)
               prefix
               ;;
    esac
    exit
}

function prefix() {
    HEIGHT=21
    WIDTH=39
    CHOICE_HEIGHT=4
    BACKTITLE="Al-Amin Zone"
    TITLE="Termux Prefix Switcher (version 1.3)"
    MENU="See [termux-prefix-switcher help] for more information"

    OPTIONS=(1 "*  Help        *"
             2 "*  Switch      *"
             3 "*  Revert      *"
             4 "*  Check Arch  *"
             5 "* <•> Exit <•> *")

    CHOICE=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --title "$TITLE" \
                    --menu "$MENU" \
                    $HEIGHT $WIDTH $CHOICE_HEIGHT \
                    "${OPTIONS[@]}" \
                    2>&1 >/dev/tty)

    clear
    case $CHOICE in
            1)
                print-help
                ;;
            2)
                switch
                ;;
            3)
                revert
                ;;
            4)
                termux_arch
                ;;
            5)
                print_prefix_banner || :
                echo "You have successfully logged out."
                exit
                ;;
    esac
    exit
}

function excute_bin() {
    if [ -f $HOME/termux-prefix-switcher ]; then
         if [ -f $PREFIX/bin/termux-prefix-switcher ]; then
             rm -f $PREFIX/bin/termux-prefix-switcher
         fi
         echo "\$HOME/termux-prefix-switcher \$1" >> $PREFIX/bin/termux-prefix-switcher && chmod +x $PREFIX/bin/termux-prefix-switcher
         printf "${green}Prefix Switcher Excuted${reset}\n"
    fi
}

function print_banner() {
    clear
    printf "${yellow} .#############################################.\n"
    printf "${yellow}.##'              ${light_cyan}Al-Amin Zone${yellow}               '##.\n"
    printf "${yellow}##' ${green}         db             88888888888888   ${yellow} '##\n"
    printf "${yellow}##  ${green}        d88b                      .d8'   ${yellow}  ##\n"
    printf "${yellow}##  ${green}       d8''8b                   .d8'     ${yellow}  ##\n"
    printf "${yellow}##  ${green}      d8'  '8b                .d8'       ${yellow}  ##\n"
    printf "${yellow}##  ${green}     d8YaaaaY8b             .d8'         ${yellow}  ##\n"
    printf "${yellow}##  ${green}    d8''''''''8b          .d8'           ${yellow}  ##\n"
    printf "${yellow}##  ${green}   d8'        '8b       .d8'             ${yellow}  ##\n"
    printf "${yellow}##. ${green}  d8'          '8b      88888888888888   ${yellow} .##\n"
    printf "${yellow}'##.        ${light_cyan}Creator By Shahinur Al-Amin${yellow}      .##'\n"
    printf "${yellow} '############### ${red}PREFIX-SWITCHER${yellow} #############'${reset}\n\n"
}

function print_prefix_banner() {
    clear
    printf "${light_cyan}★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★\n"
    printf "${light_cyan}★                                               ★\n"
    printf "${light_cyan}★   #####.  #####.  #####  #####  ###   #   #   ★\n"
    printf "${light_cyan}★   #    #  #    #  #      #       #     # #    ★\n"
    printf "${light_cyan}★   #####'  #####'  ####   ####    #      #     ★\n"
    printf "${light_cyan}★   #       #   #   #      #       #     # #    ★\n"
    printf "${light_cyan}★   #       #    #  #####  #      ###   #   #   ★\n"
    printf "${light_cyan}★                                               ★\n"
    printf "${light_cyan}★                  [ SWITCHER ]                 ★\n"
    printf "${light_cyan}★_______________________________________________★\n"
    printf "${light_cyan}★________________[ ${green}Al-Amin Zone ${light_cyan}]_______________★\n"
    printf "${light_cyan}*************************************************${reset}\n\n"
}

##################################
##              Main            ##

# Add some colours
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'

cd $HOME
case "$1" in
	h*p|H*p|H*P)
		print-help
		;;
	s*ch|S*ch|S*CH)
		switch
		;;
	r*t|R*t|R*T)
		revert
		;;
	*Y*|*y*)
		print_prefix_banner
                get_version
                bootstrap_dir
                excute_bin
                prefix
		;;
        *)
                print_prefix_banner
                get_version
                welcome_voice
                excute_bin
                prefix
                ;;
esac
